### ISSUE TITLE
群图片上传错误

### ISSUE THREAD

**Issue by BlackBird-BB** [Excaive/miraicle#5]
``` python
def get_dmoe():
    seq = ["http://www.dmoe.cc/random.php", "http://api.mtyqx.cn/tapi/random.php", "http://api.mtyqx.cn/api/random.php"]
    dmoe = random.choice(seq)
    # dmoe = requests.get(dmoe)
    # dmoe = base64.b64encode(dmoe.text.encode())
    return dmoe

@miraicle.Mirai.receiver('NudgeEvent')
def nudge_handler(bot: miraicle.Mirai, msg: miraicle.GroupMessage):
    dmoe = get_dmoe()
    print("From python:")
    img = miraicle.Image(url=dmoe)
    bot.send_group_msg(group=msg['subject']['id'], msg=[miraicle.At(qq=msg['fromId']),
                                                        img])
```

报错：

> E/net.mamoe.mirai-api-http: java.lang.IllegalStateException: upload group image failed with reason para error
java.lang.IllegalStateException: upload group image failed with reason para error
	at net.mamoe.mirai.internal.contact.GroupImpl.uploadImage(GroupImpl.kt:177)
	at net.mamoe.mirai.internal.contact.GroupImpl$uploadImage$1.invokeSuspend(GroupImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Excaive** [comment]
直接用随机图片 api 来构造 Image 是不行的，应当传入图片的 url
你可以这样修改：

``` python
def get_dmoe():
    seq = ["http://www.dmoe.cc/random.php", "http://api.mtyqx.cn/tapi/random.php", "http://api.mtyqx.cn/api/random.php"]
    dmoe = random.choice(seq)
    response = requests.get(dmoe, params={'return': 'json'})
    if response.ok:
        return response.json()['imgurl']


@miraicle.Mirai.receiver('NudgeEvent')
def nudge_handler(bot: miraicle.Mirai, msg):
    dmoe = get_dmoe()
    if dmoe:
        img = miraicle.Image(url=dmoe)
        bot.send_group_msg(group=msg['subject']['id'], msg=[miraicle.At(qq=msg['fromId']), img])
```

**Comment by BlackBird-BB** [comment]
好的~谢谢，我尝试一下~我尝试使用miraicle来复现mirai社区的部分插件，如果完成了，有无商店之类的地方共享？还有就是，，API写快点！！！

**Comment by Excaive** [comment]
到时候我新建一个 md 文件吧，如果想要共享，pull request 就行

也可以在 [Mirai Forum](https://mirai.mamoe.net/) 上面分享插件

API 文档我近期会尽快补上的

**Comment by BlackBird-BB** [comment]
能不能提供一个您的联系方式，想向您请教一些问题\~谢谢

**Comment by Excaive** [comment]
联系方式的话，因为这个地方是公开的，直接在这里留可能不太好，但是又不知道怎么给你_(:τ」∠)_

**Comment by BlackBird-BB** [comment]
唔\~好吧，这是我的邮箱（我不是很在意这个……毕竟平时不是很常用邮箱
602198790@qq.com
